### ISSUE TITLE
IllegalStateException in RecursiveDNSClient.queryRecursive

### ISSUE THREAD

**Issue by Flowdalic** [rtreffer/minidns#43]
[Smack user report](https://community.igniterealtime.org/thread/59857)

Sometimes I got IllegalStateException in RecursiveDNSClient using Smack 4.2.0-beta3-SNAPSHOT
I think I was not detected earlier.
 
```
Fatal Exception: java.lang.IllegalStateException
       at java.util.ArrayList$Itr.remove(ArrayList.java:844)
       at de.measite.minidns.recursive.RecursiveDNSClient.queryRecursive(RecursiveDNSClie nt.java:185)
       at de.measite.minidns.recursive.RecursiveDNSClient.queryRecursive(RecursiveDNSClie nt.java:180)
       at de.measite.minidns.recursive.RecursiveDNSClient.queryRecursive(RecursiveDNSClie nt.java:138)
       at de.measite.minidns.recursive.RecursiveDNSClient.query(RecursiveDNSClient.java:1 04)
       at de.measite.minidns.recursive.ReliableDNSClient.query(ReliableDNSClient.java:102 )
       at de.measite.minidns.AbstractDNSClient.query(AbstractDNSClient.java:121)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:63)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:52)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:46)
       at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.lookupSRVRecords0(MiniD nsResolver.java:75)
       at org.jivesoftware.smack.util.dns.DNSResolver.lookupSRVRecords(DNSResolver.java:4 5)
       at org.jivesoftware.smack.util.DNSUtil.resolveDomain(DNSUtil.java:187)
       at org.jivesoftware.smack.util.DNSUtil.resolveXMPPServiceDomain(DNSUtil.java:136)
       at org.jivesoftware.smack.AbstractXMPPConnection.populateHostAddresses(AbstractXMP PConnection.java:609)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPC onnection.java:552)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection. java:882)
       at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.ja va:372)
```

**Comment by Flowdalic** [comment]
Should be fixed with https://github.com/rtreffer/minidns/commit/638b8bf9132de8939b0b534e0cb3dce1389734a4#diff-b452e54c3388d15a59787914a2013c0cR274
