### ISSUE TITLE
NullPointerException on attempt to read from field 'de.measite.minidns.DNSMessage.responseCode'

### ISSUE THREAD

**Issue by grigoryfedorov** [rtreffer/minidns#53]
Some of our user encounter this error very often. 
Android 6.0.1 Samsung Galaxy S7 Edge, Smack 4.2.0-rc4-SNAPSHOT (but seems encountered much earlier).

> Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'de.measite.minidns.DNSMessage$RESPONSE_CODE de.measite.minidns.DNSMessage.responseCode' on a null object reference
       at de.measite.minidns.hla.ResolverResult.<init>(ResolverResult.java:33)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:46)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:40)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:34)
       at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.lookupHostAddress0(MiniDnsResolver.java:112)
       at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.lookupSRVRecords0(MiniDnsResolver.java:92)
       at org.jivesoftware.smack.util.dns.DNSResolver.lookupSRVRecords(DNSResolver.java:48)
       at org.jivesoftware.smack.util.DNSUtil.resolveDomain(DNSUtil.java:187)
       at org.jivesoftware.smack.util.DNSUtil.resolveXMPPServiceDomain(DNSUtil.java:136)
       at org.jivesoftware.smack.AbstractXMPPConnection.populateHostAddresses(AbstractXMPPConnection.java:626)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:556)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
       at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)

**Comment by Flowdalic** [comment]
That one is actually more tricky than #54. MiniDNS should never return `null` as result. Either there is an Timeout, then we should throw an Exception, or there is a result (incl. error results like NXDOMAIN). I'm on it, but this will require more time.

**Comment by Flowdalic** [comment]
Ok, I think I've a quick solution for MiniDNS 0.2 with 1b5021c. But once that is in master, we should break MiniDNS's habit of returning 'null'.
