### ISSUE TITLE
NullPointerException in DNSClient.query (Attempt to get length of null array)

### ISSUE THREAD

**Issue by grigoryfedorov** [rtreffer/minidns#54]
This error we've encountered only once.
Android 6.0.1 Samsung Galaxy S7 Edge, Smack 4.2.0-rc4-SNAPSHOT

> Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at de.measite.minidns.DNSClient.query(DNSClient.java:102)
       at de.measite.minidns.iterative.ReliableDNSClient.query(ReliableDNSClient.java:96)
       at de.measite.minidns.AbstractDNSClient.query(AbstractDNSClient.java:145)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:44)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:40)
       at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:34)
       at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.lookupSRVRecords0(MiniDnsResolver.java:72)
       at org.jivesoftware.smack.util.dns.DNSResolver.lookupSRVRecords(DNSResolver.java:48)
       at org.jivesoftware.smack.util.DNSUtil.resolveDomain(DNSUtil.java:187)
       at org.jivesoftware.smack.util.DNSUtil.resolveXMPPServiceDomain(DNSUtil.java:136)
       at org.jivesoftware.smack.AbstractXMPPConnection.populateHostAddresses(AbstractXMPPConnection.java:626)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:556)
       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
       at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)

**Comment by Flowdalic** [comment]
That appears to be caused by `String[] findDns()` returning `null`.

**Comment by Pirdod** [comment]
Any ideas of when there might be a new release with this fix?

**Comment by Flowdalic** [comment]
As soon as Rene finds the time, see #65.

**Comment by Pirdod** [comment]
@Flowdalic @rtreffer thanks
