### ISSUE TITLE
IllegalArgumentException: "Invalid input to toASCII: ."  at  DNSName(".", false)

### ISSUE THREAD

**Issue by guerrillalg** [rtreffer/minidns#70]
Hello,
I am using the minidns library 0.2.3 over the smack 4.2.0. When I launch the application on the Android 8.0, I get the following exception at the moment of initialization of the library.
Seems, line  `public static final DNSName ROOT = new DNSName(".", false); (DNSName.java:59)` is causing the problem.
```
FATAL EXCEPTION: main
                                     Process: com.accelior.vega.debug, PID: 5814
                                     java.lang.ExceptionInInitializerError
                                         at de.measite.minidns.DNSName.from(DNSName.java:287)
                                         at de.measite.minidns.dnssec.DNSSECClient.<clinit>(DNSSECClient.java:48)
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:47)
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:38)
                                         at de.measite.minidns.hla.DnssecResolverApi.<clinit>(DnssecResolverApi.java:31)
                                         at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.<clinit>(MiniDnsResolver.java:54)
                                         at java.lang.Class.classForName(Native Method)
                                         at java.lang.Class.forName(Class.java:453)
                                         at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:218)
                                         at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:198)
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:168)
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:153)
                                         at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:119)
                                         at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
                                         at org.jivesoftware.smack.AbstractXMPPConnection.<clinit>(AbstractXMPPConnection.java:103)
                                         at org.jivesoftware.smack.tcp.XMPPTCPConnection.setUseStreamManagementDefault(XMPPTCPConnection.java:1533)
                                      Caused by: java.lang.IllegalArgumentException: Invalid input to toASCII: .
                                         at java.net.IDN.toASCII(IDN.java:112)
                                         at java.net.IDN.toASCII(IDN.java:134)
                                         at de.measite.minidns.idna.DefaultIdnaTransformator.toASCII(DefaultIdnaTransformator.java:19)
                                         at de.measite.minidns.idna.MiniDnsIdna.toASCII(MiniDnsIdna.java:18)
                                         at de.measite.minidns.DNSName.<init>(DNSName.java:103)
                                         at de.measite.minidns.DNSName.<clinit>(DNSName.java:59)
                                         at de.measite.minidns.DNSName.from(DNSName.java:287) 
                                         at de.measite.minidns.dnssec.DNSSECClient.<clinit>(DNSSECClient.java:48) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:47) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:38) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<clinit>(DnssecResolverApi.java:31) 
                                         at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.<clinit>(MiniDnsResolver.java:54) 
                                         at java.lang.Class.classForName(Native Method) 
                                         at java.lang.Class.forName(Class.java:453) 
                                         at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:218) 
                                         at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:198) 
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:168) 
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:153) 
                                         at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:119) 
                                         at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96) 
                                         at org.jivesoftware.smack.AbstractXMPPConnection.<clinit>(AbstractXMPPConnection.java:103) 
                                         at org.jivesoftware.smack.tcp.XMPPTCPConnection.setUseStreamManagementDefault(XMPPTCPConnection.java:1533) 
                                      Caused by: Found zero length lable after NamePrep.. line:  0. preContext:  . postContext: 
                                     
                                         at android.icu.impl.IDNA2003.convertToASCII(IDNA2003.java:187)
                                         at android.icu.impl.IDNA2003.convertIDNToASCII(IDNA2003.java:277)
                                         at android.icu.text.IDNA.convertIDNToASCII(IDNA.java:654)
                                         at java.net.IDN.toASCII(IDN.java:110)
                                         at java.net.IDN.toASCII(IDN.java:134) 
                                         at de.measite.minidns.idna.DefaultIdnaTransformator.toASCII(DefaultIdnaTransformator.java:19) 
                                         at de.measite.minidns.idna.MiniDnsIdna.toASCII(MiniDnsIdna.java:18) 
                                         at de.measite.minidns.DNSName.<init>(DNSName.java:103) 
                                         at de.measite.minidns.DNSName.<clinit>(DNSName.java:59) 
                                         at de.measite.minidns.DNSName.from(DNSName.java:287) 
                                         at de.measite.minidns.dnssec.DNSSECClient.<clinit>(DNSSECClient.java:48) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:47) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<init>(DnssecResolverApi.java:38) 
                                         at de.measite.minidns.hla.DnssecResolverApi.<clinit>(DnssecResolverApi.java:31) 
                                         at org.jivesoftware.smack.util.dns.minidns.MiniDnsResolver.<clinit>(MiniDnsResolver.java:54) 
                                         at java.lang.Class.classForName(Native Method) 
                                         at java.lang.Class.forName(Class.java:453) 
                                         at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:218) 
                                         at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:198) 
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:168) 
                                         at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:153) 
                                         at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:119) 
                                         at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96) 
                                         at org.jivesoftware.smack.AbstractXMPPConnection.<clinit>(AbstractXMPPConnection.java:103) 
                                         at org.jivesoftware.smack.tcp.XMPPTCPConnection.setUseStreamManagementDefault(XMPPTCPConnection.java:1533) `
```

**Comment by rtreffer** [comment]
0.2.3 was derived from the wrong branch, 0.2.4 is pushed and will be available soon(ish).

**Comment by guerrillalg** [comment]
I see, that 0.2.3 is not present in the Repository, is it true that it has been revoked?

**Comment by rtreffer** [comment]
Yes, the tag was just deleted, the nexus artifact will continue to exist. But a 0.2.4 artifact was pushed a few minutes ago and should be available as soon as the mirrors sync.

**Comment by guerrillalg** [comment]
Updated to 0.2.4, now it is working fine. Thanks for fast response.
